### PR TITLE
Translate `translations/nomenclature/nested-components/fr-fr.yml`

### PR DESCRIPTION
**Pull request by bartocc**
Translate `translations/nomenclature/nested-components/fr-fr.yml`

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
Thank you! 🎉

**Comment by bartocc** [comment]
@NullVoxPopuli any idea why this PR does appear in my #hacktoberfest count?

**Comment by NullVoxPopuli** [comment]
That's a good question. Any chance you could screenshot your hacktoberfest page? 
I've just reread all the hacktoberfest info, and I don't see what it wouldn't be counted, so I'm going to contact the hacktoberfest people next

**Comment by bartocc** [comment]
Here is is
hacktoberfest digitalocean com_profile

What's more, PR https://github.com/NullVoxPopuli/ember-cheat-sheet/pull/37 got counted in it's author's hackoberfest profile page

**Comment by NullVoxPopuli** [comment]
Awesome, thanks for the screenshot! I'll message hacktoberfest!

**Pull request merged**
